# Generated by Django 5.2.9 on 2025-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('MaND', models.AutoField(primary_key=True, serialize=False)),
                ('MaID', models.IntegerField(blank=True, null=True, unique=True)),
                ('HoND', models.CharField(blank=True, max_length=100, null=True)),
                ('TenND', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='MatKhau', max_length=255)),
                ('QuyenHan', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'NGUOI_DUNG',
                'managed': True,
            },
        ),
    ]
