# Generated by Django 5.2.9 on 2025-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
